# Generated by Django 5.0.2 on 2024-05-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hollandquestion",
            options={
                "verbose_name": "Тест на профессиональные предпочтения| Вопрос и ответы",
                "verbose_name_plural": "Тесты на профессиональные предпочтения|Вопросы ответы второго теста",
            },
        ),
        migrations.AlterModelOptions(
            name="hollandquestion_kk",
            options={
                "verbose_name": "Кәсіби артықшылық сынағы| сұрағы және жауабы",
                "verbose_name_plural": "Кәсіби артықшылық сынақтары| сұрақтары және жауабтары",
            },
        ),
        migrations.AlterModelOptions(
            name="preferencequestion",
            options={
                "verbose_name": "Тест-опросник на профориентацию| Вопрос и ответ",
                "verbose_name_plural": "Тесты-опросники на профориентацию| Вопросы и ответы",
            },
        ),
        migrations.AlterModelOptions(
            name="preferencequestion_kk",
            options={
                "verbose_name": "Кәсіптік бағдарлауға арналған Тест-сауалнама| сұрағы және жауабтары",
                "verbose_name_plural": "Кәсіптік бағдарлауға арналған Тест-сауалнамалар| сұрақтары және жауабтары",
            },
        ),
    ]
