# Generated by Django 5.0.2 on 2024-05-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0003_alter_hollandquestion_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="careeranchorquestion",
            options={
                "verbose_name": 'Тест "Якоря карьеры" | Вопрос',
                "verbose_name_plural": 'Тест "Якоря карьеры" | Вопросы',
            },
        ),
        migrations.AlterModelOptions(
            name="careeranchorquestion_kk",
            options={
                "verbose_name": 'Тест "Якоря карьеры" | сұрағы',
                "verbose_name_plural": 'Тест "Якоря карьеры" | сұрақтары',
            },
        ),
        migrations.AlterModelOptions(
            name="careeranchorresponse",
            options={
                "verbose_name": 'Тест "Якоря карьеры" | Вопрос и ответ',
                "verbose_name_plural": 'Тест "Якоря карьеры" | Вопросы и ответы',
            },
        ),
        migrations.AlterModelOptions(
            name="mapquestion",
            options={
                "verbose_name": "Тест на профессиональные предпочтения    | Вопрос и ответы",
                "verbose_name_plural": "Тест на профессиональные предпочтения | Вопросы ответы",
            },
        ),
        migrations.AlterModelOptions(
            name="mapquestion_kk",
            options={
                "verbose_name": "Тест на профессиональные предпочтения | сұрағы және жауабтары",
                "verbose_name_plural": "Тест на профессиональные предпочтения | сұрақтары және жауабтары",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "verbose_name": "Тест-опросник на профориентацию | Вопрос и ответы",
                "verbose_name_plural": "Тест-опросник на профориентацию | Вопросы и ответы",
            },
        ),
        migrations.AlterModelOptions(
            name="question_kk",
            options={
                "verbose_name": "Тест-опросник на профориентацию | сұрақтар және жауабтар",
                "verbose_name_plural": "Тест-опросник на профориентацию | сұрақтары және жауабтары",
            },
        ),
    ]
