# Generated by Django 5.0.2 on 2024-05-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0005_delete_mapquestion_delete_mapquestion_kk_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="careeranchorquestion_kk",
            options={
                "verbose_name": '4. "Мансап зәкірі" тесті | сұрағы',
                "verbose_name_plural": '4. "Мансап зәкірі"тесті | сұрақтары',
            },
        ),
    ]
